# Generated by Django 2.2.6 on 2021-04-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20210408_0916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
