# Generated by Django 2.2.6 on 2021-04-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_auto_20210412_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(help_text='Напишите описание группы', max_length=1000, verbose_name='Описание группы'),
        ),
    ]
